In [3]:
import torch
print(torch.__version__)

2.5.1


In [5]:
import numpy as np
# 수 20을 담고있는 배열 -> 0차원 텐서(스칼라)
d1=np.array(20)
print(d1.ndim) # ndim : number of dimensions => 축이 없는 0차원
print(d1.shape) # 공간의 크기가 없다 => 튜플반환

0
()


In [9]:
# 딥러닝/AI 연산 최적화
# 1D텐서 (벡터)
d1=torch.FloatTensor([1,2,3])
print(d1)
print(d1.ndim)  # 차원의 개수
print(d1.dim()) # 차원의 개수 -> 파이토치 전용 메소드
print(d1.shape) # 요소가 3인 1차원
print(d1.size())# 요소가 3인 1차원 -> 파이토치 전용 메소드

tensor([1., 2., 3.])
1
1
torch.Size([3])
torch.Size([3])


In [11]:
# 임의의 원소 5개 가지 1D 텐서
d2=torch.FloatTensor(5)
print(d2.ndim, d2.dim(), d2.shape, d2.size())

1 1 torch.Size([5]) torch.Size([5])


In [14]:
# 숫자 5 데이터를 1차원 텐서로 만듬
d222=torch.FloatTensor([5])
print(d222)

tensor([5.])


In [19]:
d22=torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
print(d22.ndim, d22.dim(), d22.shape, d22.size())

2 2 torch.Size([3, 2]) torch.Size([3, 2])


In [20]:
# 인공지능 -> 가중치 업데이트, 행렬 곱셉..대부분 소수점 단위(미세한 변화 다룸) > 실수가 기본값 (float32)

In [21]:
# 2D 텐서(matrix)
d3=torch.FloatTensor(5,4) # 5행 4열 가진 2D텐서 생성
print(d3, d3.ndim, d3.dim(), d3.shape, d3.size())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 2 2 torch.Size([5, 4]) torch.Size([5, 4])


In [24]:
t1=torch.zeros(4,3) # 4행 3열을 0으로 채우기
t2=torch.ones(4,3)  # 4행 3열을 1로 채우기
print(t1)
print(t2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [26]:
t1=torch.zeros(4,3,dtype=torch.int)
print(t1)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [29]:
# 3D 텐서 - 층(높이), 행, 열
# 컬러 이미지(채널, 높이, 너비)
d4=torch.FloatTensor(3,2,1)
print(d4, d4.ndim, d4.dim(), d4.shape, d4.size())

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]) 3 3 torch.Size([3, 2, 1]) torch.Size([3, 2, 1])


In [31]:
d5=torch.FloatTensor([[[1],[2]],[[3],[4]],[[5],[6]]])
print(d5, d5.ndim, d5.dim(), d5.shape, d5.size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 3 torch.Size([3, 2, 1]) torch.Size([3, 2, 1])


In [34]:
d1=torch.zeros(2)
d1

tensor([0., 0.])

In [36]:
d2=torch.ones(2,3,dtype=torch.double) # 2행 3열을 1로 채우기(실수)
d2

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [41]:
# full : 입력한 값에 따라 타입이 따라감
d3=torch.full((2,3),200, dtype=torch.float32) # 2행 3열을 200으로 채워라
d3.dtype

torch.float32

In [43]:
# 열 : 3
# 행 : 2 (2*3)
# 2*3 행렬이 2개 모임
d4=torch.rand(2,2,3, dtype=torch.double)
d4

tensor([[[0.6377, 0.5304, 0.4141],
         [0.4850, 0.4266, 0.4140]],

        [[0.8107, 0.7993, 0.4036],
         [0.6247, 0.4888, 0.1474]]], dtype=torch.float64)

In [49]:
# 2행 2열
d5=torch.IntTensor([[1,2],[3,4]])
d5

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [53]:
# 64비트 정수형 텐서 생성 - 인덱스, 분류 레이블
d6=torch.LongTensor(2,2)
d6

tensor([[    4929557170048, 72340172838076673],
        [         16843009,                 0]])

In [54]:
d1=torch.DoubleTensor([[1,2,3],
                       [4,5,6]])
print(d1.shape)

torch.Size([2, 3])


In [58]:
# -1은 행의 개수에 자동으로 맞춰서 계산된다
d1=d1.reshape(3,-1)
print(d1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [59]:
# view : 원소 수를 유지하면서 텐서 크기 변경할 때 쓴다.
# 값은 유지하면서, 모양만 바꾼다

In [71]:
# 1D -> 2D
x=torch.tensor([1,2,3,4,5,6]) # 1차원 텐서
# print(x, x.shape, x.ndim)
y=x.view(2,3) # 6개를 2행 3열로 바꿈
print(y, y.size())

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [75]:
# 3D -> 2D
# 평균 0, 표준편차1인 표준정규분포에서 랜덤한 실수 추출
# view : 전체 개수는 반드시 동일해야 한다!!!! -> 기존 데이터 공유
z=torch.randn(2,3,4) # 24개 원소
z2=z.view(4,6)
print(z2, z2.shape)

tensor([[ 1.2278,  0.4852, -0.4650,  0.0084, -0.4489,  1.2127],
        [ 0.2647, -1.0813,  0.2853,  0.4218,  0.1248,  1.4997],
        [ 0.3449, -1.2195,  0.0794, -0.9176, -0.1989, -0.2438],
        [-0.8563, -1.6737,  2.0423, -1.2383,  1.7640, -1.7429]]) torch.Size([4, 6])


In [76]:
x=torch.tensor([1,2,3,4,5,6])
x2=x.view(2,-1)
print(x2,x2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [77]:
d1=torch.DoubleTensor([[[1,2,3],
                       [4,5,6,]],
                       [[7,8,9,],
                        [10,11,12]]])
print(d1.size())
print(d1.size(0)) # 높이
print(d1.size(1)) # 행개수
print(d1.size(2)) # 열개수

torch.Size([2, 2, 3])
2
2
3


In [78]:
# d1 3D -> 2D로 바꾸기 -> 행은 2로 주고 열은 행을 기준으로 자동계산
d1=d1.view(2,-1)
d1

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64)

In [80]:
# 3열로 맞추기
d1=d1.view(-1,3)
d1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)

In [81]:
d1=torch.zeros(3, dtype=torch.float)
d1=d1.type(torch.int)
d1

tensor([0, 0, 0], dtype=torch.int32)

In [85]:
# 2행 4열 double로 다 1로 채운다
# float 32로 타입 변화
d1=torch.ones(2,4, dtype=torch.double)
print(d1, d1.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) torch.float64


In [86]:
# FloatTensor(32비트) / DoubleTensor(64비트) - 연산속도 느려질수있음(2배 더 정밀한 수 표현가능/메모리도 2배 더 사용함)
# FloatTensor를 더 선호

In [87]:
d2=d2.T
d2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [88]:
print(torch.arange(5))
print(torch.arange(1,15))
print(torch.arange(1,15,2))

tensor([0, 1, 2, 3, 4])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
tensor([ 1,  3,  5,  7,  9, 11, 13])


In [89]:
d1=torch.full((3,3),3)
d2=torch.full((3,3),4)
print(d1+d2)
print(d1-d2)
print(d1*d2)
print(d1/d2)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])
tensor([[0.7500, 0.7500, 0.7500],
        [0.7500, 0.7500, 0.7500],
        [0.7500, 0.7500, 0.7500]])


In [91]:
d1=np.array([[1,2],[3,4]])
print(type(d1))

# 파이토치에서 텐서, 넘파이의 array 서로 변환이 가능하다.

# 넘파이의 ndarray를 tensor객체로 변환하겠다
d2=torch.from_numpy(d1)
print(type(d2))

#텐서객체를 넘파이의 ndarray로 변환하겠다.
d3=d2.numpy()
print(type(d3))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [92]:
d1=torch.IntTensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print(d1[:,1])

# boolean indexing
d2=d1>5
print(d2)
print(d1[d2]) # d1[5보다 큰값]
print(d1[(d1>7)&(d1<10)])

tensor([2, 5, 8], dtype=torch.int32)
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([6, 7, 8, 9], dtype=torch.int32)
tensor([8, 9], dtype=torch.int32)


In [95]:
d1=torch.FloatTensor([[1,2,3],
                      [4,5,6]])
# 복사본 생성
# d2를 수정해도 원본인 d1은 그대로 유지된다(깊은 복사)
d2=d1[:2,:2].clone()
print(d2)
d2[0,1]=10
d2

tensor([[1., 2.],
        [4., 5.]])


tensor([[ 1., 10.],
        [ 4.,  5.]])

In [96]:
d1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [97]:
d1=torch.FloatTensor([1,2,3,4])
# where : 조건에 맞는 인덱스 번호 리턴
w1=torch.where(d1<4)
print(w1)
print(d1.max())
print(d1.min())
print(d1.mean())
print(d1.sum())

(tensor([0, 1, 2]),)
tensor(4.)
tensor(1.)
tensor(2.5000)
tensor(10.)


In [100]:
# *******squeeze : 차원 압축 -> 차원이 1인 축을 제거함**********
d1=torch.FloatTensor([[1],
                      [2],
                      [3]]) # 3행 1열의 2D
d1.size()

torch.Size([3, 1])

In [105]:
# 크기가 1인 차원 삭제
d2=d1.squeeze()
print(d1.dim(), d1.size())
print(d2.dim(), d2.size()) # 차원이 삭제되면서 1차원 벡터가 됨

2 torch.Size([3, 1])
1 torch.Size([3])


In [107]:
d3=torch.rand(3,2,1)
d4=d3.squeeze()
print(d3.dim(), d3.size())
print(d4.dim(), d4.size())

3 torch.Size([3, 2, 1])
2 torch.Size([3, 2])


In [108]:
d1=torch.FloatTensor([[1],[2],[3]])
print(d1.shape)

torch.Size([3, 1])


In [110]:
# 인덱스 0에다가 1차원 추가
d2=d1.unsqueeze(0) # 인덱스 0에다가 1차원 추가
print(d2.dim(), d2.shape) # [1,3,1]

d3=d1.unsqueeze(1) # 인덱스 1에다가 1차원 추가
print(d3.dim(), d3.shape) # [3,1,1]

3 torch.Size([1, 3, 1])
3 torch.Size([3, 1, 1])


In [115]:
d1=torch.randn(1,3,1,5)
d2=d1.squeeze(0) # 모든 1인 차원 다 제거됨
print(d1.shape, d2.shape)
d3=d1.squeeze(2)
print(d2.shape)

torch.Size([1, 3, 1, 5]) torch.Size([3, 1, 5])
torch.Size([3, 1, 5])
