In [1]:
import numpy as np

a = np.array([1, 2, 3])              # shape (3,)
B = np.array([[4, 5], [6, 7], [8, 9]])  # shape (3, 2)

result = a @ B
print(result)   # [40 46]
print(result.shape)  # (2,)


[40 46]
(2,)


In [32]:
import torch

x = torch.full((2, ), 2)    # shape=(2,) -> 벡터 [2,2]
print(x)
A = torch.full((4, 3, 2), 3)   #shape=(4,3,2)
print(A)
result = torch.matmul(A, x) #(3,2)(2,) => (3,)
print (result, result.shape)

tensor([2, 2])
tensor([[[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[3, 3],
         [3, 3],
         [3, 3]]])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]) torch.Size([4, 3])


In [33]:

a=torch.ones((2,3))
b=torch.tensor(a)
print(a.dtype,'\t',b.dtype)

torch.float32 	 torch.float32


C:\Users\hi\AppData\Local\Temp\ipykernel_8060\1316812123.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b=torch.tensor(a)


In [11]:
a=torch.Tensor([0,1,2,3,4])
print(a.size())
print(a.dtype)
print(a.ndimension(), a.ndim)
print(a.view(5,1))
print(a.reshape(5,1))

torch.Size([5])
torch.float32
1 1
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [12]:
n_array=np.array([0.0,1.0,2.0,3.0,4.0])
t_tensor=torch.from_numpy(n_array)
t_tensor

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [13]:
back_numpy=t_tensor.numpy()
back_numpy

array([0., 1., 2., 3., 4.])

In [15]:
x=torch.randn(1)
print(x)
x.item() # 하나의 값 가져와서 일반 파이썬 수로 변경

tensor([1.4855])


1.4854518175125122

In [16]:
x=torch.tensor([1.,5.,6.])
print(x[0])
x[0].item()

tensor(1.)


1.0

In [18]:
np_slice=np.linspace(-2,2,5) # -2: 시작 2: 끝 5: 개수
np_slice

array([-2., -1.,  0.,  1.,  2.])

In [19]:
torch_slice=torch.linspace(-2,2,5) # -2: 시작 2: 끝 5: 개수
torch_slice

tensor([-2., -1.,  0.,  1.,  2.])

In [20]:
x=torch.tensor([[0,1,1],[1,0,1]]) # 2*3
y=torch.tensor([[1,1,],[1,1],[1,1]]) # 3*2

In [24]:
torch.mm(x,y) # matrix multtiplication
print(torch.matmul(x,y)) # 2*3 3*2 -> 2*2

tensor([[2, 2],
        [2, 2]])


In [27]:
x=torch.tensor([[1,2,3],[4,5,6]])
#torch.sum(x, dim=0) # 세로 합(결과의 크기가 열의 개수와  같다)
torch.sum(x, dim=1) # 가로 합(결과의 크기가 행의 개수와 같다)

tensor([ 6, 15])

In [28]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [29]:
def do_something(x, callback=None):
    x += 1
    if callback:
        x = callback(x)
    return x

print(do_something(10))          # 11
print(do_something(10, lambda x: x*2))  # 22


11
22


In [31]:
class MyDataset:
    def __init__(self, data, transform=None):
        self.data = data
        self.transform = transform  # 선택적 함수 저장

    def __getitem__(self, idx):
        sample = self.data[idx]
        if self.transform:          # 선택적 함수가 있으면 적용
            sample = self.transform(sample)
        return sample

def add_noise(x):
    return x + 1

dataset1 = MyDataset([10, 20, 30])             # transform 없음
dataset2 = MyDataset([10, 20, 30], add_noise)  # transform 있음

print(dataset1[0])  # 10
print(dataset2[0])  # 11

10
11


In [34]:
class MyList:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        print(f"__getitem__ 호출! index={index}")
        return self.data[index]

# 객체 생성
lst = MyList([10, 20, 30])

# 객체[] =>  __getitem__
# 인덱스로 접근 =>  __getitem__ 자동 호
print(lst[0])  # __getitem__ 호출! index=0 → 10
print(lst[1])  # __getitem__ 호출! index=1 → 20


__getitem__ 호출! index=0
10
__getitem__ 호출! index=1
20


In [35]:
class Adder:
    def __init__(self, n):
        self.n = n

    def __call__(self, x):
        return x + self.n

add5 = Adder(5)   # 객체 생성
print(add5(10))   # __call__ 자동 실행 → 15


15
