In [20]:
# TensorDataset : 여러 개의 텐서를 인자값으로 받아서 데이터셀처럼 다룬다
import torch
from torch.utils.data import TensorDataset, DataLoader
import numpy as np

X = np.random.randn(5, 3) # 10행 3열의 실수
Y = np.random.randint(0, 2, (5,)) # 0,1로 이루어진 1D 배열 데이터 5개

x_troch=torch.from_numpy(X) # numpy -> tensor 객체로 변환
y_torch=torch.from_numpy(Y)

# dl에서 데이터를 텐서로 만들어야 모델에 입력이 가능함
# print(X)
# print(Y)
print(x_troch, y_torch)

tensor([[-2.0727,  0.2606,  0.3582],
        [-1.6296, -0.1700, -2.2225],
        [-1.2240, -0.3668,  0.4644],
        [-0.4385,  1.2516,  0.9993],
        [ 0.9374,  0.1324, -1.1510]], dtype=torch.float64) tensor([1, 1, 0, 0, 1], dtype=torch.int32)


In [21]:
# TensorDataset -> 같은 인덱스끼리 묶어주는 역할
train_XY = TensorDataset(x_troch, y_torch)
train_XY[0] # (x_troch[0], y_torch[0])

(tensor([-2.0727,  0.2606,  0.3582], dtype=torch.float64),
 tensor(1, dtype=torch.int32))

In [22]:
dataloader=DataLoader(train_XY, batch_size=2, shuffle=True)
dataloader
# 총 샘플 수 5개 기준으로 2개씩 자름 (랜덤하게 2개씩 배치됨)
# 배치 첫번째 : 샘플 0,1 -> x_torch(2,3) ytorch(2,)
# 배치 두번째 : 샘플 2,3 -> x_torch(2,3) ytorch(2,)
# 배치 세번째 : 샘플 4 -> x_torch(1,3) ytorch(1,)

In [23]:
train_features, train_labels=next(iter(dataloader))

# 내부적으로 __getitem__ 호출됨 -> 배치 2개씩 설정해서 x,y 각각 2개씩 출력됨
print(train_features, train_labels)

tensor([[-1.6296, -0.1700, -2.2225],
        [ 0.9374,  0.1324, -1.1510]], dtype=torch.float64) tensor([1, 1], dtype=torch.int32)
