In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
a=np.zeros_like((3,4,5,6))
b=np.zeros([3,4])
print(a)
print(b)

[0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# logs : 로그확률 텐서
# targets : 정답 클래스 레이블
def NLLLoss(logs, targets):
    out=torch.zeros_like(targets, dtype=torch.float)

    for i in range(len(targets)):
        # logs[i] : i번째 샘플에 대한 모델 예측 확률
        # targets[i] : i번째 샘플의 실제 정답 인덱스
        out[i]=logs[i][targets[i]]
    # 뽑아낸 값들 다 더한 후, 전체 샘플 개수로 나눠서 평균구함
    # 확률에 로그를 취하면 음수가 되기 때문에 -> 일부러 -를 붙여 양수값으로 만듬
    # 평균 손실값
    return -out.sum()/len(out)

In [4]:
logs=torch.tensor([
    [-0.3,-1.2,-0.4,-2.5],
    [-1.3,-0.2,-0.4,-0.7],
    [-0.4,-0.7,-1.4,-0.5],
])

target=torch.tensor([2,1,3])

out=torch.zeros_like(target, dtype=torch.float)
out[0]=logs[0][target[0]]
out[1]=logs[1][target[1]]
out[2]=logs[2][target[2]]
out

tensor([-0.4000, -0.2000, -0.5000])

In [5]:
# 1.1/3 => 0.6

In [6]:
x=torch.Tensor([[0.6344,0.635,0.6235,0.9941]])
y=torch.LongTensor([1])

In [7]:
cross_entropy=torch.nn.CrossEntropyLoss()

In [8]:
loss=cross_entropy(x,y)
print(loss)

tensor(1.4861)


In [9]:
# CrossEntropyLoss
# logsoftmax (확률값(입력값에 0~1사이의 값)에 로그취함) 
# + nllloss (로그확률에서 정답에 해당하는 값만 뽑아 평균낸다)

In [18]:
# 샘플엠서 클래스들끼리 확률 계산(행방향)
log_softmax=torch.nn.LogSoftmax(dim=1)
x_log=log_softmax(x)
loss=NLLLoss(x_log, y)
print(loss)

tensor(1.4861)
