In [49]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn

In [50]:
# 2D 컨볼루션 레이어 정의
conv=nn.Conv2d(
    # channel # 1 흑백 # 3 컬러
    in_channels=1,
    out_channels=1,
    # 2*2크기의 필터(랜덤 값)
    kernel_size=2,
    # 커널이 이미지 훑을 때 한번에 한칸씩 이
    stride=1,
    padding=0,
    bias=False)
conv

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1), bias=False)

In [51]:
# Conv2d 가중치[출력채널, 입력채널, 높이, 너비]
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[-0.3710, -0.0185],
                        [ 0.2130, -0.4332]]]]))])

In [52]:
# 0번째 출력의 0번째 입력채널에 접근해서
conv.state_dict()['weight'][0][0]=torch.tensor([[1.,2.],
                                                [3.,4.]])

In [53]:
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[1., 2.],
                        [3., 4.]]]]))])

In [54]:
# 컬러 채널 16개의 특징을 찾고 싶다 => 가중치 구조
# 5번째 필터가 입력데이터의 1번채널을 훑을 때 사용하는 2*2 가중치
# [16,3,2,2] => weight[5][1]

In [55]:
sample_image=torch.tensor([[1,0,1,0],
                           [0,1,1,0],
                           [1,0,1,0],
                           [1,0,1,1]], dtype=torch.float)
sample_image.shape

torch.Size([4, 4])

In [56]:
# 차원늘림 -> Conv2e => 4차원 입력이어야함
sample_image=sample_image.unsqueeze(0).unsqueeze(0)
sample_image.shape
print(sample_image.numpy())

[[[[1. 0. 1. 0.]
   [0. 1. 1. 0.]
   [1. 0. 1. 0.]
   [1. 0. 1. 1.]]]]


In [57]:
# 4*4 이미지를 2*2 커널이 한칸씩 이동(stride=1) 가로3, 세로3
z=conv(sample_image) # 4차원 이미지가 conv 통과함 => 특징 추출
print(z.shape)

torch.Size([1, 1, 3, 3])


In [58]:
# output이 작아짐 (4*4 => 3*3)
# 입력과 똑같은 4*4로 유지하고 싶음 => 패딩!!
def out_size(W, F, T, S, poolsize=1):
    size=(W+2*P-F)/S+1
    return size if poolsize==1 else size/poolsize

In [65]:
sample_image2=torch.tensor([[1,0,1],
                            [0,1,1],
                            [1,0,1]], dtype=torch.float)
sample_image2=sample_image2.unsqueeze(0).unsqueeze(0)
sample_image2.shape

torch.Size([1, 1, 3, 3])

In [66]:
F=2
S=1
P=1

conv2=nn.Conv2d(in_channels=1, out_channels=1, kernel_size=F, stride=S, padding=P, bias=False)
z2=conv2(sample_image2)
print(z2.shape)

torch.Size([1, 1, 4, 4])


In [69]:
# pooling
sample_image3=torch.tensor([[1,0,1,4],
                            [0,1,1,2],
                            [1,0,1,4],
                            [1,1,5,3]], dtype=torch.float)
sample_image3=sample_image3.unsqueeze(0).unsqueeze(0)
sample_image3.shape

torch.Size([1, 1, 4, 4])

In [75]:
# 2*2 크기의 커널 사용, stride=2로 설정한 maxpooling 정의
max1=torch.nn.MaxPool2d(2, stride=2)

# maxpooling을 이미지에 적용하니 2*2 영역에서 최대값을 선택하여 이미지 크기를 줄임
print(max1(sample_image3))

tensor([[[[1., 4.],
          [1., 5.]]]])


In [76]:
# kernel : 2*2
# stride : 2
# [1,1,1,4]
# [2,6,5,7]
# [3,2,1,0]
# [1,1,3,6]
# [6,7]
# [3,6]

In [77]:
max11=torch.nn.AvgPool2d(2, stride=2)
print(max11(sample_image3))


tensor([[[[0.5000, 2.0000],
          [0.7500, 3.2500]]]])


In [79]:
# flattern
t=torch.tensor([[[1,2],
                 [3,4]],
                [[5,6],
                 [7,8]]])
t.shape

torch.Size([2, 2, 2])

In [80]:
flat_t=torch.flatten(t,1) # [2, 2*2]
print(flat_t.shape)
print(flat_t)

torch.Size([2, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
